# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
     - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  convertmd2rst:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'include-rst')

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@v5
    
      with:
        cache: 'pip'

    - run: git config user.name "kunderu-eurecom"
    - run: git config user.email "kunderu@eurecom.fr" 
    - run: pip install m2r
    - run: python3 md2rst.py --overwrite
    - run: git add .
    - run: git commit -m "converting markdown to rst"
    - run: git push
    
